---
title: "Data Mining Competitions"
subtitle: "Ok Cupid data - online dating"
author: Aldo Solari
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightLanguage: R
      countIncrementalSlides: false
      highlightLines: true   
---

```{r startup, include = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = T, eval=T, message=F, warning=F, error=F, comment=NA, cache=F)
```

# Outline

* Ok Cupid data

* The problem

* Features

* Evaluation

* Grading

* Timeline


---

# Ok Cupid data

* The original OkCupid dataset was created with the use of a python script that pulled the data from public profiles on www.okcupid.com. on 06/30/2012. Permission to use this data was obtained from OkCupid president and co-founder Christian Rudder under the condition that the dataset remains public.


* See [okcupid_codebook.txt](https://github.com/rudeboybert/JSE_OkCupid/blob/master/okcupid_codebook.txt) and  [Kim and Escobedo-Land (2015)](https://github.com/rudeboybert/JSE_OkCupid/blob/master/JSE.pdf) for a description of the original data

---

# The problem

* The dataset has 10000 observations divided in $n=6000$ observations for the training set and $m=4000$ observations for the test set. It contains $p=108$ predictors and the response variable (Class, with 2 levels: "other" and "stem")

* The goal is to predict whether a person's profession is in the STEM fields (science, technology, engineering, and math)

---

# Features

* *Basic features*:
age body_type diet drinks drugs education height income last_online offspring orientation pets religion sign smokes status where_state where_town religion_modifer (describe how serious they are about their choice) sign_modifer (describe how serious they are about their choice)
cpp cpp_fluently cpp_okay cpp_poorly (cpp is a programming language) lisp lisp_fluently lisp_okay lisp_poorly (lisp is a programming language) asian black hispanic_latin indian middle_eastern native_american other pacific_islander white (ethicity) essay_length (length of open text)

* *Features from open text data*:
The original OKCupid data contains open text essays related to an individual’s interests and personal descriptions. The dataset includes 70 selected words (binary variables coded 1 = word present in the open text, 0=non present) given below: <br>
art being biotech care climbing code coding company computer computers dancing data developer ender engineer engineering eyes family feynman firefly fixing friend geek geeky girl hair heart honest im internet lab laugh law listening lol love math matrix mechanical name nerd old problems programmer programming relationship robots school science scientist silicon smile software solve solving startup stephenson student systems teacher tech techie technical technology therapist true web websites wine writing

---

# Evaluation

* Submissions are evaluated by the Area Under the Curve (AUC)

* During the competition, the leaderboard displays your partial score, which is the AUC for 2000 (random) observations of the test set

* At the end of the contest, the leaderboard will display the final score, which is the AUC for the remaining 2000 observations of the test set. The final score will determine the final winner. This method prevents users from overfitting to the leaderboard

---

# Grading

The % of __points__ will be calculated as
$$\max\left(\frac{x-m}{M-m}\cdot 100, 0\right)$$
 where
* $x$ is your final score
* $M$ is the best score (among participants)
* $m$ is the benchmark score

The benchmark score is produced by the model described [here](docs/competitions/publish_example.html)

The team(s) with the best performance will give a brief ( ~ 10 mins ) description of their methods in class on November 18, 2019 (before the exam)

I reserve the right to regrade differently (meaning your % of points may be calculated differently)

---

# Timeline

Entry: October 21, 2019

Final submission: November 15, 2019

The R code used to get the predictions __must be published online__ by November 17. Read carefully the competitions [instructions](docs/competitions/Crules.html)



