---
title: "Online dating"
subtitle: "Final score"
output: html_document
---

```{r startup, include = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = T, eval=T, message=F, warning=F, error=F, comment=NA, cache=F, R.options=list(width=220))
```

```{r, echo=F}
Sys.time()
```



```{r, echo=FALSE}
library(rvest)
library(dplyr)
url <- 'http://www.bee-viva.com/competitions/online_dating'
webpage <- read_html(url)

tab = webpage %>%
  html_nodes("table") %>%
  .[3] %>%
  html_table(fill = TRUE)

tab[[1]] = tab[[1]][-which(tab[[1]]$Nome == "ilaria terzago"),]
tab[[1]] = tab[[1]][-which(tab[[1]]$Nome == "benchmark"),]


score_text = tab[[1]]$Punteggio
twodig = regmatches(score_text, gregexpr("[[:digit:]]+", score_text))
score = as.numeric(unlist(lapply(twodig, function(x) paste(x,collapse="."))))

min = 74.5
max = max(score)
Percent = ((score-min)/(max -min))*100
tab[[1]]$Percent = round(Percent,1)
tab[[1]]$Points = round(7.5*Percent/100,1)

knitr::kable(tab)
```


The Percent of points is calculated as
$$\min\left(\frac{x-74.5\%}{\max(x) - 74.5\%}, 100\%\right)$$
where $x$ is your final AUC\% score and $\max(x)$ is the best AUC\% score in the leaderboard