---
title: "caret Ensemble"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r, message=FALSE, warning=FALSE}
rm(list=ls())
library(MASS)
library(caret)
library(caretEnsemble)
```

## Create data partition

```{r, message=FALSE, warning=FALSE}
set.seed(123)
split <- createDataPartition(y=Boston$medv, p = 0.5, list=FALSE)

train <- Boston[split,]
nrow(train)

test = Boston[-split,-14]
test.y = Boston[-split,14]
nrow(test)
```

## Cross-validation settings

```{r, message=FALSE, warning=FALSE}
K = 10
my_control <- trainControl(
  method="cv",
  number=K,
  savePredictions="final",
  index=createResample(train$medv, K)
  )
```

## Models

```{r, message=FALSE, warning=FALSE}
library("rpart")
model_list <- caretList(
  medv~., data=train,
  methodList=c("lm","ctree"), 
  tuneList=list(
    rf=caretModelSpec(method="rf", tuneLength=3)
  ),
  trControl=my_control
  )

xyplot(resamples(model_list))

modelCor(resamples(model_list))
```


## Ensemble

```{r}
greedy_ensemble <- caretEnsemble(
  model_list, 
  metric="RMSE"
  )
summary(greedy_ensemble)
```

## Test MSE

```{r}
yhats <- lapply(model_list, predict, newdata=test)
lapply(yhats, function(yhat) mean((yhat - test.y)^2) )

yhat.en <- predict(greedy_ensemble, newdata=test)
mean((yhat.en - test.y)^2)
```