---
title: "Random Forests: Boston dataset"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/Users/aldosolari/Desktop/DM_off/3_ensemble/code")
```

## Create data partition

```{r, message=FALSE, warning=FALSE}
rm(list=ls())
library(MASS)

set.seed(123)
istrain = rbinom(n=nrow(Boston),size=1,prob=0.5)>0

train <- Boston[istrain,]
nrow(train)
test = Boston[!istrain,-14]
test.y = Boston[!istrain,14]
nrow(test)
```

# Correlation: bagging and random forest

```{r, message=FALSE, warning=FALSE}
library(randomForest)
set.seed(123)
fit1 = randomForest(medv ~ ., train, mtry=12, ntree=1)
yhat1 = predict(fit1, newdata=test)
fit2 = randomForest(medv ~ ., train, mtry=12, ntree=1)
yhat2 = predict(fit2, newdata=test)

plot(yhat1,yhat2)
abline(a=0,b=1)
cor(yhat1,yhat2)

fit1 = randomForest(medv ~ ., train, mtry=1, ntree=1)
yhat1 = predict(fit1, newdata=test)
fit2 = randomForest(medv ~ ., train, mtry=1, ntree=1)
yhat2 = predict(fit2, newdata=test)

plot(yhat1,yhat2)
abline(a=0,b=1)
cor(yhat1,yhat2)
```

## Variable importance 

```{r, message=FALSE, warning=FALSE}
# see ?importance type=1 of the R package randomForests
set.seed(123)
fit <- randomForest(medv ~ ., train, importance=TRUE)
varImpPlot(fit)

MSE <- mean( ( predict(fit, newdata=test) - test.y )^2 )
test.perm = test
test.perm[,"rm"] = sample(test.perm[,"rm"])
MSE.perm <- mean( ( predict(fit, newdata=test.perm) - test.y )^2 )

MSE.perm - MSE

test.perm = test
test.perm[,"chas"] = sample(test.perm[,"chas"])
MSE.perm <- mean( ( predict(fit, newdata=test.perm) - test.y )^2 )

MSE.perm - MSE
```

