---
title: "Competizioni DM 2019/20"
subtitle: Punteggi finali
output:
  pdf_document: default
  html_document: default
---

```{r startup, include = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = T, eval=T, message=F, warning=F, error=F, comment=NA, cache=F, R.options=list(width=220))
```



```{r, echo=FALSE}
library(rvest)
library(dplyr)
url <- 'http://www.bee-viva.com/competitions/online_dating'
webpage <- read_html(url)
tab = webpage %>%
  html_nodes("table") %>%
  .[3] %>%
  html_table(fill = TRUE)
tab[[1]] = tab[[1]][-which(tab[[1]]$Nome == "ilaria terzago"),]
tab[[1]] = tab[[1]][-which(tab[[1]]$Nome == "benchmark"),]
score_text = tab[[1]]$Punteggio
twodig = regmatches(score_text, gregexpr("[[:digit:]]+", score_text))
score = as.numeric(unlist(lapply(twodig, function(x) paste(x,collapse="."))))
min = 74.5
max = max(score)
Percent = ((score-min)/(max -min))*100
tab[[1]]$Percent = round(Percent,1)
tab[[1]]$online_dating = round(7.5*Percent/100,1)
#=================================
url <- 'http://www.bee-viva.com/competitions/miss_c'
webpage <- read_html(url)
tab2 = webpage %>%
  html_nodes("table") %>%
  .[3] %>%
  html_table(fill = TRUE)
tab2[[1]] = tab2[[1]][-which(tab2[[1]]$Nome == "minniz"),]
score_text = tab2[[1]]$Punteggio
twodig = regmatches(score_text, gregexpr("[[:digit:]]+", score_text))
score = as.numeric(unlist(lapply(twodig, function(x) paste(x,collapse="."))))
min = 80.5
max = 74.71
Percent = pmin( (score-min)/(max-min)*100, 100)
tab2[[1]]$Percent = round(Percent,1)
tab2[[1]]$miss_congeniality = round(7.5*Percent/100,1)
ix = match(tab[[1]]$Nome, tab2[[1]]$Nome)
tab[[1]]$sum = tab[[1]]$online_dating+tab2[[1]]$miss_congeniality[ix]
res = data.frame(nickname=tab[[1]]$Nome, online_dating=tab[[1]]$online_dating, miss_congeniality=tab2[[1]]$miss_congeniality[ix], Points = round(tab[[1]]$sum,1) )
#=================================
library(dplyr)
library(readr)
who <- read_csv("/Users/aldosolari/Documents/mygithub/DM/docs/competitions/DM competitions1920.csv")
who <- who[-which(who[,4]=="Terzago"),]
who[which(who[,4]=="Pastore"),6]<-"Jinglerry"
who[which(who[,6]=="Jingle"),6]<-"Jinglerry"
who[which(who[,4]=="Silva"),6]<-"Double_Name"
who[nrow(who)+1,]<-c("","779608","Floriana","Meluso","f.meluso1", "f.meluso1")
names(who)[6]<-"Team"
who2 = who %>%
  arrange(Team) 
who3 = who2[,c(2,3,4,5,6)]
who3[[4]][3]<-"m.musto5"
who3[[4]][9]<-"s.borgonovo3"
who3[[4]][34]<-"v.cala"
who3[[4]][16] <- "salessandro164"
ix2 = match(tab[[1]]$Nome, who3[[4]])
res$Badge = who3[[1]][ix2]
res$Nome = who3[[2]][ix2]
res$Cognome = who3[[3]][ix2]
res$Team = who3[[5]][ix2]

res = res[,c(5,2,3,4)]
res = res %>% arrange(Badge)

knitr::kable(res[-37,])
```

### Aggiustamenti dovuti al _peer rating_

836897: fattore moltiplicativo 0.6, punteggio finale 7.56 

