---
title: "Data Mining Competitions"
subtitle: "Rules"
author: Aldo Solari
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightLanguage: R
      countIncrementalSlides: false
      highlightLines: true   
---

```{r startup, include = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = T, eval=T, message=F, warning=F, error=F, comment=NA, cache=F)
```

---

# Competitions

| Name | Data | Problem | During the course | After the course |  
|---|---|---|---|---|
| Miss Congeniality | Netflix| Regression | 21.10.19 - 15.11.19 | Dec. 19 - Sept. 20 |
| Online dating | OkCupid | Classification |  21.10.19 - 15.11.19 | Dec. 19 - Sept. 20 |


---

# From 21.10.19 to 15.11.19

1. You can join the competitions only once per academic year. Your score will expire at the end of the academic year

2. The competition will be run through an automated system (Beeviva platform)

3. Students can partecipate individually, or if they attended the classes, in teams of up to three

4. You cannot use external data: the final model must be based on the data provided (but feature engineering is allowed)

5. If you use a non-standard R package, but you are expected to be able to explain what it does (on the day of the exam if required by the teacher)

6. Before 17.11.19 h. 12:00 each partecipant/team must publish on github 
      - a brief description of the analysis 
      - the reproducible R code to obtain the final predictions

7. The student/team with the best performance in each competition must give a brief (10/15 mins) presentation of their methods on 18.11.2019 h 13:30 Lab 907



---

# From December 2019 to September 2020

If you do not take part in the competitions in the period from 21.10.19 to 15.11.19, then

1. Contact the teacher via e-mail and get new training/test data

2. At least one week before the exam:
    - send via e-mail (only once) the predictions in the required format 
    - publish on github 
        - a brief description of the analysis 
        - the reproducible R code to obtain the predictions


3. You can join the competitions only once per academic year. Your score will expire at the end of the academic year

4. You cannot use external data: the final model must be based on the data provided (but feature engineering is allowed)

5. You are expected to be able to explain your analysis/code (on the day of the exam if required by the teacher)

6. If you use a non-standard R package, you are expected to be able to explain what it does (on the day of the exam if required by the teacher)

---

# What to publish on github

1. Brief description of the analysis. It must include
    - Key ideas/insights 
    - How you handled missing values
    - Feature engineering operations
    - Model(s) used for the final prediction
    - R packages used (specify if non-standard) 
    - References (if needed)

2. R code to reproduce the last submission (no comments, plots, etc. only the necessary code)

---


# Competition platform

The [competition platform](http://www.bee-viva.com/competitions) is provided by BeeViva s.r.l. If you click on a specific Competition in the listing, you will go to the Competition's homepage. The following information is provided in the tabs:

1. *Description* gives a description of the problem

2. *Data* is where you can download the data splitted into training set and test set

3. *Evaluation* describes how to format your submission file and how your submissions will be evaluated. Each competition employs a metric (RMSE, AUC, etc.) that serves as the objective measure for how competitors are ranked on the leaderboard

4. *Timeline* for joining the competition: an entry deadline and a submission deadline (after which no new submissions will be accepted). After the deadline passes, partecipants get a final score

5. *Leaderboard*. Submissions can be made through through manual upload in the competition platform. Submissions are scored immediately and summarized on a live leaderboard

---

# Working in teams

1. Only students attending the classes can work in groups of up to three. Each student may be on one team only

2. Each member of a team must be registered in the Bee-viva platform and submit at least one prediction

3. During the competition, each member of a team may submit different predictions, but the final prediction must be the same for all members of the team. If a team submit different final predictions, the one with the lowest score will be considered

5. Before 17.11.19 h. 12:00 only one member of each the team must publish on github 
      - a brief description of the analysis 
      - the reproducible R code to obtain the final predictions

7. At the end of the competition, each member must fill a peer rating form of team members. The individual score will be the team score adjusted based on peer ratings. This multiplier will range from 1.05 (for people who go above and beyond) down to 0 (for people who don’t participate)

---

# Peer rating of team members

Your name: $_________________________$ Your team: $_________________________$

Please write the names of all of your team members, INCLUDING YOURSELF, and
rate the degree to which each member fulfilled his/her responsibilities in completing the
homework assignments.

*These ratings should reflect each individual's level of participation and effort and sense of responsibility, not his or her academic ability.*

Name of the team member # 1: $_________________________$ Rating: $_________________________$

Name of the team member # 2: $_________________________$ Rating: $_________________________$

Name of the team member # 3: $_________________________$ Rating: $_________________________$

---

# Ratings

The possible ratings are as follows:


**Excellent** Consistently went above and beyond—tutored teammates, carried
more than his/her fair share of the load

**Very good** Consistently did what he/she was supposed to do, very well prepared
and cooperative

**Satisfactory** Usually did what he/she was supposed to do, acceptably prepared and
cooperative

**Ordinary** Often did what he/she was supposed to do, minimally prepared and
cooperative

**Marginal** Sometimes failed to show up or complete assignments, rarely
prepared

**Deficient** Often failed to show up or complete assignments, rarely prepared

**Unsatisfactory** Consistently failed to show up or complete assignments, unprepared

**Superficial** Practically no participation

**No show** No participation at all

---

# Code of conduct

All students must follow a **code of conduct**, which covers issues such as plagiarism, falsification, unauthorized assistance, cheating, and other grievous acts of academic dishonesty



