---
title: "Points: OkCupid (1st round)"
output: html_document
---

```{r startup, include = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = T, eval=T, message=F, warning=F, error=F, comment=NA, cache=F, R.options=list(width=220))
```




```{r, echo=FALSE}
library(dplyr)
library(readr)
who <- read_csv("/Users/aldosolari/Documents/mygithub/DM/docs/competitions/DMcompetitions.csv")
who2 = who %>% 
  rename(Team = "Team name (repeat Username if single)", TeamN = "Number of components of the team", User = "Username (BeeViva)", Badge = "Badge number")  %>% 
  arrange(Team) %>%
  select(Surname, Name, Team, User, Badge) 
who2 = who2[-c(1,38,23,33,40,48),]
who2[who2$Surname=="Missineo","Team"] = "Derek"
who2[who2$Surname=="Pirotta","Team"] = "Derek"

who2$User[9]<- "beatrice.somaschini21"
who2$User[23]<- "giabellianna"
who2$User[36]<-"e.benincasa1"
who2$User[37]<-"f.melograna1"
who2$User[44]<- "sonia_cucchi"
who2$User[45]<-"joana.curri"


library(rvest)
library(dplyr)
url <- 'http://www.bee-viva.com/competitions/ok_cupid'
webpage <- read_html(url)

tab = webpage %>%
  html_nodes("table") %>%
  .[3] %>%
  html_table(fill = TRUE)

score_text = tab[[1]]$Punteggio
twodig = regmatches(score_text, gregexpr("[[:digit:]]+", score_text))
score = as.numeric(unlist(lapply(twodig, function(x) paste(x,collapse="."))))


max = max(score)
min = min(score)
percent = (score-min)/(max-min)*100
points = round(5*percent/100,2)
results = data.frame(User=tab[[1]]$Nome, score, percent, points)
results$percent = round(results$percent ,2)

ix = match(results$User, who2$User)
pub_na = data.frame(Badge=who2$Badge[ix], Surname=who2$Surname[ix], Name=who2$Name[ix], results)
pub = pub_na[complete.cases(pub_na),]
row.names(pub) = as.character(1:nrow(pub))
knitr::kable(pub, row.names = T)
```


