---
title: "**Syllabus**"
output:
  html_document:
    theme: cosmo
    toc: yes
    toc_float: yes
---

| Insegnamento | Modulo | CFU | ID |
|----|--------|--------|--------------|
| DATA SCIENCE M | DATA MINING | 6 | 1819-2-F8204B018-F8204B034M |
| DATA MINING M  | | 6 |1819-2-F8204B014 |

# **Obiettivi formativi**

Il corso si pone come obiettivo l'acquisizione delle principali tecniche per l'esplorazione dei dati (*data mining*) e di apprendimento supervisionato (*supervised learning*) e la loro implementazione nell’ambiente di programmazione R. Durante il corso verrà data particolare enfasi al processo di modellazione dei dati per la previsione (*predictive modelling*).

Alla fine del corso lo studente sarà in grado di affrontare l'analisi di dati complessi a fini previsivi attraverso il processo di esplorazione, manipolazione e modellazione dei dati.

# **Contenuti sintetici**

Il corso integra considerazioni di carattere teorico con aspetti pratico-applicativi di analisi dei dati e di programmazione in R per facilitare la comprensione degli argomenti trattati.

* Aspetti teorici: il compromesso tra distorsione e varianza, come evitare il sovra-adattamento ai dati, combinazione di modelli, stime vincolate e penalizzate
* Aspetti applicativi: esplorazione, manipolazione e modellizzazione dei dati in R per la previsione di dati futuri

# **Programma esteso**

* Errore di previsione: il compromesso tra distorsione e varianza
* Evitare il sovra-adattamento ai dati: criteri basati sull'informazione e il metodo della convalida incrociata
* Manipolare, esplorare, visualizzare e modellare i dati nell'ambiente di programmazione R
* L'addestramento di modelli di regressione e classificazione in R: il pacchetto caret
* Stime vincolate e penalizzate: i metodi ridge e lasso
* Combinare un insieme di modelli previsivi: i metodi bagging e random forest


# **Prerequisiti** 

Si consiglia la conoscenza degli argomenti trattati nei corsi *Probabilità e Statistica Computazionale M* e *Statistica Avanzata M*.

# **Metodi didattici**

Tutte le lezioni si svolgono in laboratorio, integrando aspetti di carattere teorico con quelli pratico-applicativi di analisi dei dati e di programmazione in R.

# **Modalità di verifica dell'apprendimento**

La modalità di verifica si basa su una prova scritta/pratica (con laboratorio) ed una prova orale finale facoltativa. La prova scritta/pratica (con laboratorio) è composta da due parti:

1. scritto di teoria ed esercizi con R
2. partecipazione alle competizioni

Il voto della prova scritta/pratica (con laboratorio) è dato dai voti delle parti 1. e 2. con pesi di circa 2/3 e 1/3, rispettivamente. Qualora lo studente (oppure i docenti) richiedano la prova orale, il voto finale è una media dei voti della prova scritta/pratica (con laboratorio) e della prova orale.

La parte 1. si svolge in laboratorio. Lo "scritto di teoria" comprende domande aperte e/o domande a scelta multipla e ha come obiettivo la verifica della comprensione degli aspetti matematico-statistici degli argomenti trattati (non è consentito l'utilizzo di libri, appunti o altro materiale). Gli "esercizi con R" prevedono la risoluzione di esercizi di programmazione e/o di analisi dei dati con l'utilizzo di un computer su cui è installato il software R o RStudio e ha come obiettivo la verifica delle abilità di programmazione in R (è consentito l'utilizzo di materiale didattico fornito dal docente). 

La parte 2. si può svolgere da casa o dall'Università in una finestra temporale che precede l'appello d'esame. Il funzionamento delle competizioni è il seguente: con l'avvio della gara vengono resi disponibili i dataset per i quali bisogna costruire dei modelli previsivi e contestualmente viene fissata una scadenza. Per tutto il periodo della competizione gli studenti possono sottomettere le proprie previsioni, le quali vengono valutate con un punteggio.  La partecipazione alle competizioni ha l'obiettivo di mettere alla prova lo studente con l'analisi di dati complessi provenienti da diversi ambiti (marketing, finanza, medicina, etc.). Agli studenti frequentanti viene data l'opportunità di svolgere le competizioni in gruppi di massimo 3 persone.


# **Testi di riferimento**

* Course repository: https://github.com/aldosolari/DM
* Gareth, Witten, Hastie, Tibshirani (2013). Introduction to Statistical Learning with applications in R. Springer
* Azzalini, Scarpa (2004). Analisi dei dati e data mining. Springer-Verlag Italia
* Kuhn, Johnson (2013). Applied Predictive Modelling. Springer
* Wickham, Grolemund (2015) R for Data Science. O'Reilly Cookbooks
* Clark (2018) Introduction to Machine Learning. https://m-clark.github.io/introduction-to-machine-learning/
* Carmichael (2018) Introduction to Data Science. https://idc9.github.io/stor390/

# **Periodo di erogazione dell’insegnamento**

Primo semestre, primo ciclo.

# **Teaching language**

Le lezioni si svolgono in italiano, tuttavia la maggior parte dei libri di testo e il materiale didattico è in lingua inglese.